#%RAML 1.0 DataType
type: array
items:
  properties:
    Name__c:
      type: string
      required: false
    Age__c: 
      type: number
      required: true
    Address__c: 
      type: string
      required: false
    Gender__c:
      type: string
      required: false


