#%RAML 1.0 DataType
type: array
items:
  properties:
    Id:
      type: string
      required: true
    Name__c?:
      type: string
    Age__c?: 
      type: number
    Address__c?: 
      type: string 
    Gender__c?:
      type: string
      
